export const SEACH_ICON = 'fas fa-search'
export const EMAIL_ICON = 'fal fa-envelope'
export const EYE_SLASH_ICON = 'fal fa-eye-slash'
export const EYE_ICON = 'fal fa-eye'
export const USER_ICON = 'fal fa-user'